baseURL = 'https://koday.me/'
languageCode = 'en-us'
title = "Yuya's Portfolio"
theme = 'gokarna'
enableRobotsTXT = true
enableEmoji = true

[params]
avatarURL = "https://avatars.githubusercontent.com/u/29038315"
socialIcons = [
  { name = "github", url = "https://github.com/ponkio-o" },
  { name = "x", url = "https://twitter.com/ponkio_o" },
  { name = "bluesky", url = "https://bsky.app/profile/koday.me" },
  { name = "linkedin", url = "https://www.linkedin.com/in/yuya-koda/" },
  { name = "facebook", url = "https://www.facebook.com/y.koda0301/" },
  { name = "speakerdeck", url = "https://speakerdeck.com/ponkio_o" },
]

# Analytics
customHeadHTML = '''
    <script defer src="https://cloud.umami.is/script.js" data-website-id="2a98467c-39db-4414-bcf9-f9f779d98102"></script>
  '''
